[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn config.wsgi:application --timeout 60 --bind 0.0.0.0:8080 --log-level debug"
healthcheckPath = "/health/"
healthcheckTimeout = 100 