[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && gunicorn config.wsgi:application --timeout 300 --bind 0.0.0.0:8080 --log-level debug --capture-output --enable-stdio-inheritance"
healthcheckPath = "/health/"
healthcheckTimeout = 100 