# Generated by Django 5.1.3 on 2024-12-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='query_count',
            field=models.IntegerField(default=0),
        ),
    ]
